### ISSUE TITLE
Hardcoded `PREFIX` in Slurm and Munge builds generate invalid paths

### ISSUE THREAD

**Issue by jedel1043** [charmed-hpc/slurm-snap#11]
Setting `prefix=/` at build time for Slurm generates incorrect paths that are baked at build time by Slurm. Examples:

![image](https://github.com/charmed-hpc/slurm-snap/assets/38230983/4ff8595d-244d-4e3f-94c2-894f14107456)

![image](https://github.com/charmed-hpc/slurm-snap/assets/38230983/a9160ced-3bcb-45b6-954b-8ae8485e9223)

Setting both `LibPrefix` and `AuthInfo` serves as a workaround, but it would be good to see if we can patch this to have correct default values.

**Comment by NucciTheBoss** [comment]
Unfortunately this is a limitation with the `autotools` plugin that I have run up against multiple times, especially when working with C-based code bases like Apache httpd and nginx. Many programs will bake the `prefix` into the source code during configuration and use those as the default paths if there's no additional configuration.

For example, if I didn't set the prefix, Slurm would likely bake in the path `/root/parts/slurm/install/lib/slurm`. `httpd` does something similar in the Ondemand snap, but I fix it by using a wrapper to point directly to the paths I want it to find. I see us having two possible solutions here:

1. Set the munged socket path and plugin path at configure time. Slurm has quite a few configure options. I do something like this for nginx.
2. During snap installation, auto-generate a _slurm.conf_ file that sets the socket and plugin path to the correct locations. We can just do this in the `install` hook. I do something like this with the Ondemand snap.

Best bet is to probably first start with option 1 and then try option 2 if those configuration options are not available with the configure script.

**Comment by jedel1043** [comment]
Found another one
![image](https://github.com/charmed-hpc/slurm-snap/assets/38230983/0c5c864b-6243-4a96-ada4-46b378d2955d)

**Comment by NucciTheBoss** [comment]
The `mungekey` issue will be fixed in https://github.com/charmed-hpc/slurm-snap/issues/14 by including a wrapper (or configure change) to point to the correct directory.

Regarding the Slurm location issues, I did not find an option that enables me to set specific values at configure time before building Slurm. Easiest fix here is to just autogenerate those _slurm.conf_ options in the `install` hook, and then have some complimenting documentation that indicates why we generate those options automatically and why you're strongly discouraged from changing them.

**Comment by NucciTheBoss** [comment]
#18 slightly addresses this issue specifically with the munge key location and plugin dir, but there's still likely merits to automatically generating a basic _slurm.conf_ file that includes info on how to configure munge. If a site isn't using configless mode, it would be good for us to already have set for where to look for the munged socket.

`mungekey` likely just requires a wrapper that points to the correct location.

**Comment by NucciTheBoss** [comment]
Actually, we can tell Slurm where to look by default for the munged service socket by using the `--with-munge-socket` configure option when building Slurm.

**Comment by NucciTheBoss** [comment]
This issue is fixed by #24 as Slurm is now able to find to the `PluginDir` and the munge key file without additional configuration - _requires extra settings in the `configure` script_ - and we have a path forward for fixing the munge key command by fleshing out the configuration API for munge in #14
