### ISSUE TITLE
[Bug]: Preseeded slurm.conf conflicts with slurm.conf retrieved from controller when in configless mode

### ISSUE THREAD

**Issue by jedel1043** [charmed-hpc/slurm-snap#27]
Right now the snap creates an empty file at startup time. However, a small papercut of this is that if the slurmd is transitioned into configless mode, the daemon will try to load the empty file, even if the config has been already fetched from slurmctld. This adds a manual step of having to delete the file manually.

Technically this could be solved by deleting the file if the user sets the `slurm.config-server` option. Though, this could cause problems for users that had an extensive config there, since it would make it harder to unroll the change in case the user wants to return to the classic behaviour. Maybe this won't be a problem; the config file is replicated between the controller and all the nodes, which should be pretty easy to do manually; but I think it would be good to think about this before implementing a solution that deletes or modifies the config file.

**Comment by NucciTheBoss** [comment]
I consider this a bug within in the snap. The install hook will seed an empty _slurm.conf_ file when the snap is first installed. This file isn't actually required since the snap still needs some additional configuration before Slurm is ready to get "slurmy."

It would be better if we just created the file when an administrator actually sets a configuration parameter for _slurm.conf_ rather than seed an empty file at install time. This then allows us to throw an error if the administrator sets a configuration parameter when slurmd is configured to run in configless/dynamic mode, and gives us the ability to automatically delete the file when configless mode is enabled.
