### ISSUE TITLE
[Enhancement] Way to setup config from stdin and/or file

### ISSUE THREAD

**Issue by jedel1043** [charmed-hpc/slurm-snap#36]
As an improvement to integrate with the Slurm charms, we need to have a way to set multiple configurations using either input or a file. This should make it really easy to bulk-modify a lot of settings without having to call `snap set slurm` for each one of the modified setting.

**Comment by NucciTheBoss** [comment]
I'm going to close this one out. We discussed over Mattermost that `snap set ...` enables us to set multiple configs at once so that we don't have to call `snap set slurm ...` one-by-one for each configuration we want to update:

```shell
$ snap set slurm config.value1=... config.value2=... config.value3=... ...
```

I think it could potentially be an interesting discussion for us to add the ability to export your configuration from one snap to and import into another, but I think the charmed operators and `snap get -d` enable us to do this pretty easily right now for our needs, so I think this discussion should happen later down the line and potentially in a separate issue.
